CanalTP\SamEcoreUserManagerBundle\Entity\User:
    type: entity
    table: public.t_user_usr
    fields:
        id:
            column: usr_id
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        firstName:
            column: usr_first_name
            type: string
            length: 255
        lastName:
            column: usr_last_name
            type: string
            length: 255
        timezone:
            column: usr_timezone
            type: string
            length: 255
        locked:
            column: usr_locked
            type: boolean
        status:
            column: usr_status
            type: integer
        expired:
            column: usr_expired
            type: boolean
        expiresAt:
            column: usr_expires_at
            type: datetime
            nullable: true
        credentialsExpired:
            column: usr_credentials_expired
            type: boolean
        credentialsExpireAt:
            column: usr_credentials_expire_at
            type: datetime
            nullable: true
    uniqueConstraints:
        username_idx:
            columns: [ username, username_canonical ]
        email_idx:
            columns: [ email, email_canonical ]
    manyToOne:
        customer:
            targetEntity: CanalTP\NmmPortalBundle\Entity\Customer
            inversedBy: users
            nullable: true
            joinColumn:
                name: cus_id
                referencedColumnName: cus_id
    manyToMany:
        userRoles:
            targetEntity: CanalTP\SamCoreBundle\Entity\Role
            inversedBy: users
            joinTable:
                name: public.tj_user_role_ur
                joinColumns:
                    usr_id:
                        referencedColumnName: usr_id
                inverseJoinColumns:
                    rol_id:
                        referencedColumnName: rol_id
